# maintained by ChimpanziCloud (boii ts tuff)
# chances of working:0.1%

# sigma flags (build flags)
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
RELAX_USES_LIBRARY_CHECK=true
DEVICE_PATH := device/motorola/vienna

# maintainer info
BOARD_MAINTAINER_NAME := ChimpanziCloud
TW_DEVICE_VERSION := $(BOARD_MAINTAINER_NAME)
OF_MAINTAINER := $(BOARD_MAINTAINER_NAME)
PB_MAIN_VERSION := $(BOARD_MAINTAINER_NAME)

# pbrp flags
PB_DISABLE_DEFAULT_DM_VERITY := true
PB_TORCH_PATH := "/sys/devices/virtual/flashlight_core/flashlight/flashlight_torch"
PB_TORCH_MAX_BRIGHTNESS := 1

# twrp flags
TWRP_EVENT_LOGGING := true
TWRP_INCLUDE_LOGCAT := true
TW_DEFAULT_LANGUAGE := en
TW_USE_TOOLBOX := true
TW_OEM_BUILD := true
TW_NO_EXFAT := true
TW_NO_LEGACY_PROPS := true
TW_HAS_DOWNLOAD_MODE := false
TW_USE_COMPRESSION := true
TW_INCLUDE_FASTBOOTD := true
TW_STATUS_ICONS_ALIGN := center
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_CUSTOM_BATTERY_PATH := "/sys/devices/platform/smart_battery/power_supply/battery/capacity"
TW_MAX_BRIGHTNESS := 2000
TW_DEFAULT_BRIGHTNESS := 400
TW_FRAMERATE := 60
TW_NO_SCREEN_BLANK := true
TW_CUSTOM_CPU_TEMP_PATH := "/sys/devices/virtual/thermal/thermal_zone11/temp"
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := false
TARGET_USES_MKE2FS := true
TW_DEVICE_VERSION := v0.41.67 | ChimpanziCloud # boi 67 so tuff
TW_INCLUDE_FB2PNG := true  
TW_INCLUDE_NTFS_3G := true  
TW_INCLUDE_FUSE_EXFAT := true 
TW_INCLUDE_FUSE_NTFS := true 
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_LPTOOLS := true
TW_EXCLUDE_APEX := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_PYTHON := true
TW_HAS_MTP := true
TW_USB_STORAGE := true
TW_NO_FASTBOOT_BOOT := true
TW_SUPPORT_INPUT_AIDL_HAPTICS := true
TW_SUPPORT_INPUT_AIDL_HAPTICS_FQNAME := "IVibrator/default"
TW_BACKUP_EXCLUSIONS := "/data/fonts/files"
TW_USE_LEGACY_BATTERY_SERVICES := true

#crypto flags (for encryption, not for cryptocurrency duh)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
TW_FORCE_KEYMASTER_VER := true
OF_DEFAULT_KEYMASTER_VERSION := 4.1

# android phone info
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_OTA_ASSERT_DEVICE := vienna
TARGET_KERNEL_ARCH := $(TARGET_ARCH)
TARGET_KERNEL_HEADER_ARCH := $(TARGET_ARCH)
PRODUCT_PLATFORM := mt6878
TARGET_BOARD_PLATFORM := mt6878
TARGET_BOOTLOADER_BOARD_NAME := vienna
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := true
TARGET_USES_LOGD := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_RAMDISK_USE_LZ4 := true
LZMA_RAMDISK_TARGETS := boot,recovery
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_VENDOR_RAMDISK_FRAGMENTS := recovery
BOARD_VENDOR_RAMDISK_FRAGMENT.recovery.MKBOOTIMG_ARGS := --ramdisk_type RECOVERY
BOARD_VENDOR_SEPOLICY_DIRS := $(DEVICE_PATH)/vendor_sepolicy
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := 
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USES_VENDOR_DLKMIMAGE := true

# config
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_USES_METADATA_PARTITION := true
BOARD_PREBUILT_BOOTIMAGE := $(DEVICE_PATH)/prebuilt/boot.img
BOARD_BOOT_HEADER_VERSION := 4
BOARD_PAGE_SIZE := 4096
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x07c88000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_DTB_OFFSET := 0x07c88000
BOARD_DTB_SIZE := $(stat -L -c %s $(TARGET_PREBUILT_DTB))
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
BOARD_VENDOR_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_AVB_ENABLE := true
TARGET_COPY_OUT_SYSTEM := system
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_SYSTEM_DLKM := system_dlkm
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
TARGET_RECOVERY_DEVICE_DIRS := $(DEVICE_PATH)
TARGET_NO_KERNEL := true
TARGET_RECOVERY_PIXEL_FORMAT := BGRA_8888
TARGET_FORCE_PREBUILT_KERNEL := true
RECOVERY_SDCARD_ON_DATA := true

# mkbootimg config
BOARD_MKBOOTIMG_ARGS += \
    --dtb $(TARGET_PREBUILT_DTB) \
    --dtb_offset $(BOARD_DTB_OFFSET) \
    --vendor_cmdline $(BOARD_VENDOR_CMDLINE) \
    --pagesize $(BOARD_PAGE_SIZE) --board "" \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --tags_offset $(BOARD_TAGS_OFFSET) \
    --base $(BOARD_KERNEL_BASE) \
    --header_version $(BOARD_BOOT_HEADER_VERSION)
    

# partitioning
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_USERDATAIMAGE_PARTITION_SIZE := 230833017324
BOARD_SUPER_PARTITION_SIZE := 22300852224
BOARD_SUPER_PARTITION_GROUPS := motorola_dynamic_partitions
BOARD_MOTOROLA_DYNAMIC_PARTITIONS_SIZE := 22296657920
BOARD_MOTOROLA_DYNAMIC_PARTITIONS_PARTITION_LIST := \
product \
system \
system_ext \
vendor \
# workarounds for fails
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

# bypass anti-rollback (adrian betrayed the eeffoc gang)
PLATFORM_SECURITY_PATCH := 2099-12-31
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
PLATFORM_VERSION := 99.87.36
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
