# orangefox build flags rahh
OF_HIDE_NOTCH := 1
OF_QUICK_BACKUP_LIST := /boot;/data;/system_image;/vendor_image;
OF_DEFAULT_KEYMASTER_VERSION := 4.1
OF_PATCH_AVB20 := 1
OF_KEEP_FORCED_ENCRYPTION := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_USE_LEGACY_TIME_FIXUP := 1
OF_OPTIONS_LIST_NUM := 9
