export LC_ALL="C"
export FOX_BUILD_DEVICE=vienna
export FOX_VIRTUAL_AB_DEVICE=1
export OF_DEFAULT_KEYMASTER_VERSION=4.1
export OF_USE_LZMA_COMPRESSION=1
export OF_SKIP_FBE_DECRYPTION=0
export OF_NO_RELOAD_AFTER_DECRYPTION=1
export FOX_DRASTIC_SIZE_REDUCTION=1
